try {
console.log(naoExisto);
} catch(err) {
  console.log('naoExito n√£o existe.');
  console.log(err);
}
